export default {
  rearSprocket: "Sprocket {{number}}",
  frontSprocket: "Sprocket {{number}}",
  rearSprockets: "Rear Sprockets",
  frontSprockets: "Front Sprockets",
  favoriteCadence: "Favorite Cadence [rpm]",
  tireCircumference: "Tire circumference [mm]",
  preferences: "Preferences",
  test: "test",
  reset: "Reset",
  speed: "Speed [km/h]",
  transmissionTarget: "Target transmission",
  transmissionBest: "Best possible transmission",
  cadenceActual: "Actual cadence [rpm]",
  cadenceDifference: "Difference to facorite cadence [rmp]",
  gearTable: "Tabular View",
};
