export default {
  rearSprocket: "Ritzel {{number}}",
  frontSprocket: "Blatt {{number}}",
  rearSprockets: "Ritzel (hinten)",
  frontSprockets: "Blätter (vorne)",
  favoriteCadence: "Gewünschte Trittfrequenz [U/min]",
  tireCircumference: "Reifenumfang [mm]",
  preferences: "Einstellungen",
  test: "test",
  reset: "Zurücksetzen",
  speed: "Geschwindigkeit [km/h]",
  transmissionTarget: "Soll-Übersetzung",
  transmissionBest: "Bestmögliche Übersetzung",
  cadenceActual: "Tatsächliche Trittfrequenz [U/min]",
  cadenceDifference: "Abweichung von gewünschter Trittfrequenz [U/min]",
  gearTable: "Tabellarische Ansicht",
};