export default {
  appName: "GearControl",
  appDescription: "The app for everyone who does not want to be Too-Tired when being Two-Tired!",
  rearSprocket: "Ritzel {{number}}",
  frontSprocket: "Blatt {{number}}",
  rearSprockets: "Ritzel (hinten)",
  frontSprockets: "Blätter (vorne)",
  favoriteCadence: "Gewünschte Trittfrequenz [U/min]",
  tireCircumference: "Reifenumfang [mm]",
  preferences: "Einstellungen",
  test: "test",
  reset: "Zurücksetzen",
  speed: "Geschwindigkeit [km/h]",
  speedUnit: "km/h",
  transmissionTarget: "Soll-Übersetzung",
  transmissionBest: "Bestmögliche Übersetzung",
  cadenceActual: "Tatsächliche Trittfrequenz [U/min]",
  cadenceDifference: "Abweichung von gewünschter Trittfrequenz [U/min]",
  gearTable: "Tabellarische Ansicht",
  impressum: "Impressum",
  quote: "Arbeitserleichterung, Bequemlichkeit und das Streben nach Perfektion sind die Triebfedern der meisten Entdeckungen und Erfindungen.",
  team: "Unser Team",
  teamDescription: "Wir bei 'Two-Tired' sind zwei Freunde aus der Region Köln-Bonn die Spaß am und während dem Programmieren haben!",
  bikeSpecific: "Fahrrad",
  userSpecific: "Fahrer"
};